export default [
  {
    "_id": "6a5375eec55cef36ed5510c3",
    "name": "MiniMercado",
    "order": 0,
    "providerTypeId": "6a536333c55cef36ed55108a",
    "description": "Estabelecimento comercial de pequena ou média dimensão que oferece produtos essenciais para o consumo diário, proporcionando conveniência e rapidez aos clientes.",
    "iconUrl": "",
    "isActive": false,
    "motives": [],
    "originFloors": [],
    "loadingHelpOptions": [],
    "requiresPhotos": false,
    "pricingMode": "PROVIDER_DEFINED",
    "allowNegotiation": false,
    "minProviderPrice": 0,
    "maxProviderPrice": 0,
    "hourlyRateEnabled": false,
    "materialFeeEnabled": false,
    "baseFare": 0,
    "pricePerKm": 0,
    "serviceCommission": 10,
    "serviceFee": 0,
    "percentageFee": 0,
    "requiresVehicleType": false,
    "supportsHelpers": false,
    "vehicleTypes": [],
    "createdAt": "2026-07-12T11:09:34.450Z",
    "updatedAt": "2026-07-27T11:33:56.802Z",
    "__v": 0
  },
  {
    "_id": "6a537d74c55cef36ed551114",
    "name": "Reboque",
    "order": 2,
    "providerTypeId": "6a537593c55cef36ed5510b7",
    "description": "Transporte e assistência para veículos avariados, acidentados ou impossibilitados de circular, com atendimento rápido e seguro até ao destino solicitado.",
    "iconUrl": "car-crash",
    "isActive": true,
    "motives": [
      "Veículo avariado",
      "Veículos acidentado",
      "Transporte de carro para oficinas",
      "Auxílio em situações de emergência",
      "Guincho para veículos bloqueados",
      "Transporte de veículos entre localidades"
    ],
    "originFloors": [],
    "loadingHelpOptions": [],
    "requiresPhotos": false,
    "pricingMode": "PROVIDER_DEFINED",
    "allowNegotiation": false,
    "minProviderPrice": 0,
    "maxProviderPrice": 0,
    "hourlyRateEnabled": false,
    "materialFeeEnabled": false,
    "baseFare": 0,
    "pricePerKm": 0,
    "serviceCommission": 10,
    "serviceFee": 0,
    "percentageFee": 0,
    "requiresVehicleType": false,
    "supportsHelpers": false,
    "vehicleTypes": [
      "6a523939419f4828d30fff00"
    ],
    "createdAt": "2026-07-12T11:41:40.566Z",
    "updatedAt": "2026-07-27T11:33:42.933Z",
    "__v": 0
  },
  {
    "_id": "6a538617c55cef36ed551142",
    "name": "Gás ao Domicílio",
    "order": 1,
    "providerTypeId": "6a537593c55cef36ed5510b7",
    "description": "Entrega de gás de cozinha de forma rápida, segura e conveniente onde estiver",
    "iconUrl": "",
    "isActive": false,
    "motives": [
      "Galp - 10KG"
    ],
    "originFloors": [],
    "loadingHelpOptions": [],
    "requiresPhotos": false,
    "pricingMode": "PROVIDER_DEFINED",
    "allowNegotiation": false,
    "minProviderPrice": 0,
    "maxProviderPrice": 0,
    "hourlyRateEnabled": false,
    "materialFeeEnabled": false,
    "baseFare": 0,
    "pricePerKm": 0,
    "serviceCommission": 10,
    "serviceFee": 0,
    "percentageFee": 0,
    "requiresVehicleType": false,
    "supportsHelpers": false,
    "vehicleTypes": [
      "6a53611bc55cef36ed550fed"
    ],
    "createdAt": "2026-07-12T12:18:31.233Z",
    "updatedAt": "2026-07-27T11:33:42.933Z",
    "__v": 0
  },
  {
    "_id": "6a538776af6f6071bc5060c4",
    "name": "Mudanças e Cargas",
    "order": 3,
    "providerTypeId": "6a537593c55cef36ed5510b7",
    "description": "Serviços de mudanças para transporte de pertences com segurança e acompanhamento durante todo o percurso.",
    "iconUrl": "dolly",
    "isActive": true,
    "motives": [
      "Mudança de casa",
      "Mudança de escritórios",
      "Mudança de armazéns",
      "Transporte de Cargas",
      "Carregamento e descarregamento",
      "Transporte de Material de Construção ",
      "Entulho",
      "Outro"
    ],
    "originFloors": [],
    "loadingHelpOptions": [
      "Transporte",
      "Transporte + Carregamento"
    ],
    "requiresPhotos": false,
    "pricingMode": "AUTO_PLUS_PROVIDER",
    "allowNegotiation": false,
    "minProviderPrice": 0,
    "maxProviderPrice": 0,
    "hourlyRateEnabled": false,
    "materialFeeEnabled": false,
    "baseFare": 0,
    "pricePerKm": 0,
    "serviceCommission": 10,
    "serviceFee": 0,
    "percentageFee": 0,
    "requiresVehicleType": false,
    "supportsHelpers": false,
    "vehicleTypes": [
      "6a53611bc55cef36ed550fed"
    ],
    "createdAt": "2026-07-12T12:24:22.188Z",
    "updatedAt": "2026-07-27T11:33:42.933Z",
    "__v": 0
  },
  {
    "_id": "6a5388b398c76935d0190efd",
    "name": "Carro",
    "order": 4,
    "providerTypeId": "6a537593c55cef36ed5510b7",
    "description": "Compras de supermercados (rancho), entrega de  compras em lojas, cargas pesadas entre outros",
    "iconUrl": "truck-loading",
    "isActive": true,
    "motives": [
      "Compras de supermercado ",
      "Transporte de carga",
      "Rancho",
      "Motorista Particular"
    ],
    "originFloors": [],
    "loadingHelpOptions": [],
    "requiresPhotos": false,
    "pricingMode": "AUTO",
    "allowNegotiation": false,
    "minProviderPrice": 0,
    "maxProviderPrice": 0,
    "hourlyRateEnabled": false,
    "materialFeeEnabled": false,
    "baseFare": 0,
    "pricePerKm": 0,
    "serviceCommission": 10,
    "serviceFee": 0,
    "percentageFee": 0,
    "requiresVehicleType": false,
    "supportsHelpers": false,
    "vehicleTypes": [
      "6a523938419f4828d30ffefe"
    ],
    "createdAt": "2026-07-12T12:29:39.277Z",
    "updatedAt": "2026-07-27T11:33:42.933Z",
    "__v": 0
  },
  {
    "_id": "6a538ad098c76935d0190f19",
    "name": "Mototaxistas e Delivers",
    "order": 1,
    "providerTypeId": "6a537593c55cef36ed5510b7",
    "description": "Transporte de produtos, documentos, encomendas  e pessoas de forma rapida e com comodidade.",
    "iconUrl": "",
    "isActive": true,
    "motives": [
      "Entrega de comida",
      "Entrega de compras de supermercados",
      "Entrega de medicamentos",
      "Entrega de documentos",
      "Transporte de passageiro (Mototaxi)"
    ],
    "originFloors": [],
    "loadingHelpOptions": [],
    "requiresPhotos": false,
    "pricingMode": "AUTO",
    "allowNegotiation": false,
    "minProviderPrice": 0,
    "maxProviderPrice": 0,
    "hourlyRateEnabled": false,
    "materialFeeEnabled": false,
    "baseFare": 0,
    "pricePerKm": 0,
    "serviceCommission": 10,
    "serviceFee": 0,
    "percentageFee": 0,
    "requiresVehicleType": false,
    "supportsHelpers": false,
    "vehicleTypes": [
      "6a523938419f4828d30ffefc"
    ],
    "createdAt": "2026-07-12T12:38:40.401Z",
    "updatedAt": "2026-07-27T11:33:42.933Z",
    "__v": 0
  },
  {
    "_id": "6a6742178b04d814a3bf95ea",
    "name": "Camião de Limpeza de Fossas",
    "order": 0,
    "providerTypeId": "6a537593c55cef36ed5510b7",
    "description": "Resolva rapidamente problemas de fossas cheias, entupidas ou com mau cheiro.",
    "iconUrl": "truck",
    "isActive": true,
    "motives": [],
    "originFloors": [],
    "loadingHelpOptions": [],
    "requiresPhotos": false,
    "pricingMode": "AUTO_PLUS_PROVIDER",
    "allowNegotiation": false,
    "minProviderPrice": 0,
    "maxProviderPrice": 0,
    "hourlyRateEnabled": false,
    "materialFeeEnabled": false,
    "baseFare": 0,
    "pricePerKm": 0,
    "serviceCommission": 0,
    "serviceFee": 0,
    "percentageFee": 0,
    "requiresVehicleType": false,
    "supportsHelpers": false,
    "vehicleTypes": [
      "6a53611bc55cef36ed550fed"
    ],
    "createdAt": "2026-07-27T11:33:43.074Z",
    "updatedAt": "2026-07-27T11:33:43.074Z",
    "__v": 0
  }
];
